### ISSUE TITLE
Failed to install using `install_github("wbaopaul/rGMAP")`

### ISSUE THREAD

**Issue by ningbioinfo** [wbaopaul/GMAP#5]
Hi I am getting this error when trying to install rGMAP from github.
And also same error when I git clone the repo and compress it into a .tar.gz file and install it.
```
> install_github("wbaopaul/rGMAP")
Downloading GitHub repo wbaopaul/rGMAP@master
from URL https://api.github.com/repos/wbaopaul/rGMAP/zipball/master
Installing rGMAP
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/_4/4vskhkkj0kbcw7x8bfg9c8br0000gn/T/RtmpRphxKn/devtools138fe48cc1e16/wbaopaul-rGMAP-c3627ff'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library'  \
  --install-tests 

* installing *source* package ‘rGMAP’ ...
** libs
make: Nothing to be done for `all'.
installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rGMAP/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘rGMAP’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rGMAP/libs/rGMAP.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rGMAP/libs/rGMAP.so, 6): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rGMAP/libs/rGMAP.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rGMAP/libs/rGMAP.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rGMAP’
Installation failed: Command failed (1)
```

**Comment by wbaopaul** [comment]
@ningbioinfostruggling Which platform you used? Linux? or MAC? I only tested it on Linux Redhat. 

You can download the source code package (rGMAP_1.3.1.tar.gz) and install directly. (not git colon and compressed). I have provided the download link. Then in R:
install.packages('your full path to rGMAP_1.3.1.tar.gz', type = 'source', rep = NULL)

**Comment by ningbioinfo** [comment]
in MAC. 
Yeah that works but that link needs to be updated since the tiny bug of plotting multiple chr is fixed and I wanted to write rGMAP into a pipeline where I want to do something like 
```
if (!require("rGMAP")) install.packages("rGMAP")
```

**Comment by wbaopaul** [comment]
@ningbioinfostruggling I think I did update the link with the fixed bug of plotting multiple chromosomes. You can still use rGMAP in your pipeline by adding rGMAP_1.3.1.tar.gz to your pipeline, right? something like:

`if (!require("rGMAP")) install.packages("your pipeline fold holding rGMAP_1.3.1.tar.gz", type = 'source', rep = NULL)`

I am still not sure why the installation failed on MAC, probably the compiler environment?

**Comment by ningbioinfo** [comment]
yeah probably is the MAC compiler problem, I tried it in my ubuntu and it's fine. And yeah guess I'll add a wget for MAC users in the pipeline then.
